---
title: Statistical inference using weights and survey design
subtitle: 3. Stata examples
author: 
  name: Pierre Walthéry
institute: UK Data Service

date: "October 2025"
date-format: MMMM YYYY
brand: _brand.yml
include-after-body:
  - text: |
      <script type="text/javascript">
      window.addEventListener('load', function() {
      var logo = document.querySelector('.slide-logo');
      # var url = 'https://ukdataservice.ac.uk';
      logo.style.cursor = 'pointer';
      logo.addEventListener('click', function() {
      window.open(url, '_blank');
          });
        });
      </script>
  
format: 
  revealjs:
    scrollable: true
    logo: 
      path: "pics/UKDS_Logos_Col_Grey_300dpi.png"
      href: "https://ukdataservice.ac.uk"
      alt: "UK Data Service logo"
    css: ukds25.css
    embed-resources: true
    smaller: true
    transition: zoom
    background-transition: fade
filters:
  - reveal-header

jupyter: nbstata
---
  
## Survey design in Stata
  
  - Stata provides comprehensive support for computing survey design-informed  estimates from survey data
- Implementation logic similar to R:
  
  - Declare the survey design using svyset

- `svyset id=psu_var [pweights=weight_var],strata(strata_var)`

- Use `svy:` - prefixed commands for estimation:
  
  - `svy:mean myvar`, `svy:tab myvar` etc...

## Stata command-based weighting  - 1

- Users may add sampling weights to most Stata estimation commands, or use survey-specific commands. The latter is recommended. 

- Stata distinguishes between four kinds of (dealing with) weights: 
  
  - frequency weights (`fweight`), 
  - analytical weights (`aweight`), 
  - importance weights (`iweight`) and 
  - probability weights (`pweight`). 

- These mostly differ in the way standard errors are computed 


  

## Stata command-based weighting  - 2

- Survey weights should be treated as *probability weights* or `pw`. 

- Key estimation commands, such as `summarise` or `tab` do not allow using `pw`:  this is to nudge users to rely on the `svy:` commands instead
.
- 'On the fly' weighting (i.e. not using survey design functions) in Stata consists in the weighting variables being specified between square brackets. 

- `stata_command myvar [pw=weight_var]`

- It is tempting to to specify instead the wrong  kind of weights function  (`fw` or `aw`) if one does not wish to use the survey design functions. You may get the correct point estimates, but your standard errors are likely to be incorrect  Do this at your own risk

## Question 3
- What would be the consequences of:
  
  - weighing but not accounting for the sample design; 
- neither using  weights or accounting for the survey design?
  
  - When: 
    - inferring the mean age in the population?
    - computing the uncertainty  of this  estimate? 
  
## Stata version
- Opening the dataset and declaring the survey design (scroll down for full output)

```{stata stata_1}

use ~/Data/bsa/UKDA-8450-stata/bsa2017_for_ukda.dta,clear

svyset Spoint [pw=WtFactor], strata(StratID) 
```
##
- Computing the survey design-informed  version of the mean...

```{stata stata_1.1}

svy: mean RAgeE
```
## 
- And the other two versions: 
```{stata stata_1.2}

  mean RAgeE [pw=WtFactor]
mean RAgeE
```

## Answer - Stata

- Not using weights results in  overestimating the mean age in the population (of those aged 18+) by about 4 years. 
- This might be due to the fact that older respondents are more likely to take part to surveys. 
# - Using command-based weighting does not alter the value of the estimated population mean when compared with SD informed estimates...
- ... but would lead us to overestimating the precision/underestimate the uncertainty of our estimate -- by about plus or minus 3 months. 

## Computing a proportion and its 95% confidence interval

```{stata Stata_4}
** Creating a dummy variable for significant interest in politics
quietly recode Politics 1 2 =1 3/8=0,gen(Politics2) 
** Survey-design informed frequencies...
svy:ta Politics2  
```

##
- ... Proportions and CIs
```{stata Stata_4.1}
svy:ta Politics2, percent ci 
```
## Question 4
- What is the proportion of respondents aged 17-34 in the sample, as well as its 95% confidence interval? 
  
  - You can use `RAgecat5`

## Answer

-  Same for age categories

```{stata Stata_4.2}

svy:ta RAgecat5, percent ci                         
```


## Question 5
- What is the 95% confidence interval for the proportion of people significantly interested in politics in the North East? 
- Is the proportion likely to be different in London? In what way? 
- What is the region of the UK for  the estimates are likely to be least precise?

## Not accounting for domain estimation

```{stata Stata_5.1}
svy:prop Politics2 if GOR_ID==1, percent  cformat(%9.1f)
```

## ... And  accounting for it
- % interested in politics in the North East...

```{stata Stata_5.2}
svy,subpop(if GOR_ID==1):prop Politics2, percent  cformat(%9.1f)
```

##
- ... And in London

```{stata Stata_5.2.1}
svy,subpop(if GOR_ID==7):prop Politics2, percent  cformat(%9.1f)
```

##

- Alternative syntax

```{stata Stata_5.2.2}
svy:prop Politics2,over(GOR_ID) percent  cformat(%9.1f)
```

## Question 6
- Using interest in politics as before, and three category age `RAgecat5`: 
  
  - Produce a table showing the proportion of respondents significantly interested in politics by age group and gender
- Assess whether the age difference in interest for politics is similar for each gender.
- Is it fair to say that men aged under 35 are more likely to declare being  interested  in politics  than women aged 55 and above?
  
## Answer

```{stata Stata_6}
*  Men under 35
svy,subpop(if RAgecat5==1 & Rsex==1):prop Politics2 ,percent  cformat(%9.1f) 
* Women 55+ 
  svy,subpop(if RAgecat5==3 & Rsex==2):prop Politics2, percent  cformat(%9.1f) 
```

##

- Contrast with: 
  
```{}
svy: tab  Politics2 if RAgecat5==1 & Rsex==1, percent ci 

```

#  Alternative syntax
```{stata Stata_6.1}
egen RagSex=group(RAgecat5 Rsex),label // Creates age groups by sex variable

svy: prop Politics2,over(RagSex ) percent   cformat(%9.1f) 

```


